# Pasta com os wallpapers do slideshow
# vazio = /usr/share/backgrounds/chililinux
WALLPAPER_DIR=/usr/share/backgrounds/chililinux

# Intervalo em segundos
INTERVAL=60

# Controle do slideshow
# yes | no | true | false | 0 | 1
DISABLED=no

# Wallpaper fixo (caminho completo da imagem)
# vazio = slideshow com os wallpapers da pasta
FIXED_WALLPAPER=
