#!/bin/sh
exec 2>&1

INTERVAL=600
COMMAND="/usr/local/bin/chili-change-gnome-wallpaper"

PATH=/usr/local/bin:/usr/bin:/bin
export PATH

echo "chili-wallpaper service iniciado"

while :; do
    if [ -x "$COMMAND" ]; then
        echo "$(date): Executando comando..."
        "$COMMAND"
    else
        echo "$(date): ERRO: comando não executável"
    fi

    sleep "$INTERVAL"
done
